services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: pulse
      POSTGRES_PASSWORD: pulse_dev
      POSTGRES_DB: pulse
    ports:
      - '5432:5432'
    volumes:
      - pulse_pg:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U pulse -d pulse']
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 5

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: pulseminio
      MINIO_ROOT_PASSWORD: pulseminio_dev
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - pulse_minio:/data

volumes:
  pulse_pg:
  pulse_minio:
