// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from './routes.js';
import type { ResolvingMetadata, ResolvingViewport } from 'next/types.js';

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default:
    | React.ComponentType<{ params: Promise<ParamMap[Route]> } & any>
    | ((
        props: { params: Promise<ParamMap[Route]> } & any,
      ) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>);
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[];
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata,
  ) => Promise<any> | any;
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport,
  ) => Promise<any> | any;
  metadata?: any;
  viewport?: any;
};

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default:
    | React.ComponentType<LayoutProps<Route>>
    | ((
        props: LayoutProps<Route>,
      ) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>);
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[];
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata,
  ) => Promise<any> | any;
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport,
  ) => Promise<any> | any;
  metadata?: any;
  viewport?: any;
};

// Validate ../../web/src/app/(app)/chats/[chatId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<'/chats/[chatId]'>> = Specific;
  const handler = {} as typeof import('../../web/src/app/(app)/chats/[chatId]/page.js');
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../web/src/app/(app)/chats/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<'/chats'>> = Specific;
  const handler = {} as typeof import('../../web/src/app/(app)/chats/page.js');
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../web/src/app/(app)/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<'/profile'>> = Specific;
  const handler = {} as typeof import('../../web/src/app/(app)/profile/page.js');
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../web/src/app/(app)/sessions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<'/sessions'>> = Specific;
  const handler = {} as typeof import('../../web/src/app/(app)/sessions/page.js');
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../web/src/app/(app)/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<'/settings'>> = Specific;
  const handler = {} as typeof import('../../web/src/app/(app)/settings/page.js');
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../web/src/app/(app)/users/[userId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<'/users/[userId]'>> = Specific;
  const handler = {} as typeof import('../../web/src/app/(app)/users/[userId]/page.js');
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../web/src/app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<'/login'>> = Specific;
  const handler = {} as typeof import('../../web/src/app/(auth)/login/page.js');
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../web/src/app/(auth)/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<'/onboarding'>> = Specific;
  const handler = {} as typeof import('../../web/src/app/(auth)/onboarding/page.js');
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../web/src/app/(auth)/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<'/signup'>> = Specific;
  const handler = {} as typeof import('../../web/src/app/(auth)/signup/page.js');
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../web/src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<'/'>> = Specific;
  const handler = {} as typeof import('../../web/src/app/page.js');
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../web/src/app/(app)/chats/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<'/chats'>> = Specific;
  const handler = {} as typeof import('../../web/src/app/(app)/chats/layout.js');
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../web/src/app/(app)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<'/'>> = Specific;
  const handler = {} as typeof import('../../web/src/app/(app)/layout.js');
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../web/src/app/(auth)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<'/'>> = Specific;
  const handler = {} as typeof import('../../web/src/app/(auth)/layout.js');
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../web/src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<'/'>> = Specific;
  const handler = {} as typeof import('../../web/src/app/layout.js');
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}
